--- !ditz.rubyforge.org,2008-03-06/project
name: p4est
version: "0.4"
components:
- !ditz.rubyforge.org,2008-03-06/component
  name: p4est
releases:
- !ditz.rubyforge.org,2008-03-06/release
  name: "0.3"
  status: :unreleased
  release_time:
  log_events:
  - - 2008-10-16 17:36:04.252955 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - created
    - Release 0.3 should have full 2D and 3D functionality.
- !ditz.rubyforge.org,2008-03-06/release
  name: "0.4"
  status: :unreleased
  release_time:
  log_events:
  - - 2008-10-16 19:05:39.234410 Z
    - Carsten Burstedde <carsten@ices.utexas.edu>
    - created
    - Publish p4est including all code necessary for Deal.II
